- name : Configure Docker on test-server Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: Updating ec2 instance
    command : sudo apt update

  - name : Install Docker
    command : sudo apt install docker.io -y

  - name : Start Docker Service
    command : sudo systemctl start docker

  - name : Run the Bank application
    command: sudo docker run -itd -p 8084:8081 swethamba859/banking-project:1.0
